/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var HopIn:String = "event:/Music/HopIn";
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var BirdBomb:String = "event:/SFX/Bird/BirdBomb";
    public static inline var BirdHit:String = "event:/SFX/Bird/BirdHit";
    public static inline var CrateDrop:String = "event:/SFX/Crate/CrateDrop";
    public static inline var CrateGet:String = "event:/SFX/Crate/CrateGet";
    public static inline var CrateLand:String = "event:/SFX/Crate/CrateLand";
    public static inline var BalloonDeflate:String = "event:/SFX/Deflate/BalloonDeflate";
    public static inline var BalloonDeflateEndClick:String = "event:/SFX/Deflate/BalloonDeflateEndClick";
    public static inline var BalloonFire:String = "event:/SFX/Fire/BalloonFire";
    public static inline var FireworksExplosion:String = "event:/SFX/Fireworks/FireworksExplosion";
    public static inline var FireworksFire:String = "event:/SFX/Fireworks/FireworksFire";
    public static inline var BalloonLand:String = "event:/SFX/Land/BalloonLand";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var ScoreFour:String = "event:/SFX/Score/ScoreFour";
    public static inline var ScoreOne:String = "event:/SFX/Score/ScoreOne";
    public static inline var ScoreThree:String = "event:/SFX/Score/ScoreThree";
    public static inline var ScoreTwo:String = "event:/SFX/Score/ScoreTwo";
    public static inline var ScoreZero:String = "event:/SFX/Score/ScoreZero";
    public static inline var Shoot:String = "event:/SFX/Shoot/Shoot";
    public static inline var ShootDirection:String = "event:/SFX/Shoot/ShootDirection";
    public static inline var ShootGround:String = "event:/SFX/Shoot/ShootGround";
    public static inline var Splash:String = "event:/SFX/Splash/Splash";
    public static inline var SplashSmall:String = "event:/SFX/Splash/SplashSmall";
    public static inline var TruckExplosion:String = "event:/SFX/Truck/TruckExplosion";
}
